/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.BD.ParteBD;
import  Parse.*;
import UML.Parte;
import himevico2.controladora;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Iker
 */
public class panelFiltroParte extends javax.swing.JFrame {
    Parte Pa;

    /**
     * Creates new form panelFiltroParte
     */
    public panelFiltroParte() {
        initComponents();
        this.setResizable(false); 
         setLocationRelativeTo(null);
          ArrayList<String>ldni=new ArrayList();
            try{
                  ldni=controladora.mostrarDni();
         
                     for(int x=0;x<ldni.size();x++){
        
                            combodni.insertItemAt(ldni.get(x),x);
            
                             }}
        catch(Exception e){JOptionPane.showMessageDialog(null,"error en la vista");}
    
    }
 public panelFiltroParte(Parte P) {
     Pa=P;
        initComponents();
        this.setResizable(false); 
         setLocationRelativeTo(null);
          ArrayList<String>ldni=new ArrayList();
            try{
                  ldni=controladora.mostrarDni();
         
                     for(int x=0;x<ldni.size();x++){
        
                            combodni.insertItemAt(ldni.get(x),x);
            
                             }}
        catch(Exception e){JOptionPane.showMessageDialog(null,"error en la vista");}
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combodni = new javax.swing.JComboBox<>();
        fecha2 = new com.toedter.calendar.JCalendar();
        fecha1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 430));
        getContentPane().setLayout(null);

        combodni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        combodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodniActionPerformed(evt);
            }
        });
        getContentPane().add(combodni);
        combodni.setBounds(10, 30, 140, 20);
        getContentPane().add(fecha2);
        fecha2.setBounds(190, 210, 250, 121);
        getContentPane().add(fecha1);
        fecha1.setBounds(190, 40, 240, 121);

        jLabel1.setText("Dni Trabajador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 120, 14);

        jLabel3.setText("Fecha Inicio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 90, 110, 14);

        jLabel4.setText("Fecha Fin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 270, 140, 14);

        jLabel5.setText("* Seleccione una o varias");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 350, 220, 14);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 350, 100, 23);

        jButton2.setText("Salir");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(313, 350, 100, 23);

        jButton3.setText("Generar Informe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 170, 240, 23);

        jLabel6.setText("Seleccione mes para el informe");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 240, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/imagenes/arenaG.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        controladora.acabarV();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(combodni.getSelectedItem().toString().isEmpty()==true)
        controladora.consultaP(combodni.getSelectedItem().toString(),fecha1.getDate(), fecha2.getDate());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combodniActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    
   
    DOMParserPartes dpe = new DOMParserPartes();
     try{
        dpe.runExample();}
     catch(Exception e){}
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelFiltroParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelFiltroParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelFiltroParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelFiltroParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelFiltroParte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combodni;
    private com.toedter.calendar.JCalendar fecha1;
    private com.toedter.calendar.JCalendar fecha2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
