/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import himevico2.controladora;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Iker
 */
public class panelViaje extends javax.swing.JFrame {
private static Date date;
private static int idP;
     
    /**
     * Creates new form panelViaje
     */
    public panelViaje() {
        initComponents();
         setLocationRelativeTo(null);
        this.setResizable(false); 
        
      
       
    }
     public panelViaje(int idParte) {
        idP=idParte; 
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false); 
        
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        talbaran = new javax.swing.JTextField();
        bAñadir = new javax.swing.JButton();
        bcerrar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        thoraIni = new javax.swing.JSpinner();
        thoraFin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 250));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        jLabel1.setText("VIAJE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 84, 30);

        jLabel2.setText("Hora fin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 80, 30);

        jLabel3.setText("Albaran");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 80, 16);

        jLabel4.setText("Hora Inicio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 90, 80, 30);
        getContentPane().add(talbaran);
        talbaran.setBounds(110, 60, 140, 26);

        bAñadir.setText("Añadir Viaje");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(bAñadir);
        bAñadir.setBounds(10, 180, 120, 29);

        bcerrar.setText("Cerrar Viajes");
        bcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bcerrar);
        bcerrar.setBounds(130, 180, 123, 29);

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver);
        volver.setBounds(270, 180, 83, 29);

        thoraIni.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        thoraIni.setEditor(new javax.swing.JSpinner.DateEditor(thoraIni, "hh:mm"));
        getContentPane().add(thoraIni);
        thoraIni.setBounds(110, 90, 80, 26);

        thoraFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        thoraFin.setEditor(new javax.swing.JSpinner.DateEditor(thoraFin, "hh:mm"));
        getContentPane().add(thoraFin);
        thoraFin.setBounds(110, 130, 80, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
     Date date1=new Date();
     Date date2=new Date();
     

// TODO add your handling code here:
          //ava.sql.Date fechasql = new java.sql.Date(   thoraIni.getValue().toString());
    //hay que parsear las horas
   try{ 
   String fecha1 =  thoraIni.getValue().toString();
DateFormat formatter = new SimpleDateFormat("HH:mm");
 date1 = formatter.parse(fecha1);
   String fecha2 =  thoraFin.getValue().toString();
 formatter = new SimpleDateFormat("HH:mm");
 date2 = formatter.parse(fecha2);}
   catch (Exception e){}
/*
       
*/
     controladora.subirVI(talbaran.getText(),date1, date2,idP);
    
    }//GEN-LAST:event_bAñadirActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        controladora.iniciarP("abierto");
    }//GEN-LAST:event_volverActionPerformed

    private void bcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcerrarActionPerformed
                controladora.iniciarP("cerrado");
        // TODO add your handling code here:
    }//GEN-LAST:event_bcerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bcerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField talbaran;
    private javax.swing.JSpinner thoraFin;
    private javax.swing.JSpinner thoraIni;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
