/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import UML.Parte;
import UML.Vehiculo;
import himevico2.controladora;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Iker
 */
public class panelParte extends javax.swing.JFrame {
private static String finalizado;
private static String estadoV,dni_trabaja;
 private static Date fecha;
 private static Vehiculo V;
 private static Parte P;
         
 /**
     * Creates new form panelParte
     */
    public panelParte() {
       finalizado="f";
        initComponents();
        this.setResizable(false); 
        setLocationRelativeTo(null);
        
           ArrayList<String>lcen=new ArrayList();
            setLocationRelativeTo(null);
            try{
                  lcen=controladora.mostrarV();
         
                     for(int x=0;x<lcen.size();x++){
        
                            comboV.insertItemAt(lcen.get(x),x);
            
                             }}
        catch(Exception e){JOptionPane.showMessageDialog(null,"error en la vista");}
                }
 public panelParte(String estadoviaje,String dni_trabajador) {
     //recibo estadoviajes para hacer inset con estado abierto o cerrado
     //recibo dni para la insert del parte
         V=controladora.vehiculoVacio();
          finalizado="f";
          estadoV=estadoviaje;
          dni_trabaja=dni_trabajador;
          
        initComponents();
        this.setResizable(false); 
        setLocationRelativeTo(null);
        
        //chequeo en la base si algun parte con f para ese dni
     /*  P=controladora.partenocerrado(dni_trabajador);
        if (P.toString().isEmpty()==false){
            tkmini.setText(P.getKmInicio().toString());
            tkmfin.setText(P.getKmFinal().toString());
            tgasoil.setText(P.getGasoil().toString());
            tautopis.setText(P.getAutopista().toString());
            tdietas.setText(P.getDietas().toString());
            totros.setText(P.getOtrosGastos().toString());
            thoras.setText(P.getHorasTrabajadas().toString());
            comboV.setSelectedItem(P.getV().getMatricula());
            tincidencias.setText(P.getIncidencias()); */
        
        
        //sacar listado de vehiculos en stock    
           ArrayList<String>lVehiculo=new ArrayList();
            setLocationRelativeTo(null);
            try{
                 lVehiculo=controladora.mostrarV();
         
                     for(int x=0;x<lVehiculo.size();x++){
        
                            comboV.insertItemAt(lVehiculo.get(x),x);
            
                             }}
        catch(Exception e){JOptionPane.showMessageDialog(null,"error en la vista");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tkmini = new javax.swing.JTextField();
        tkmfin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tdietas = new javax.swing.JTextField();
        tautopis = new javax.swing.JTextField();
        totros = new javax.swing.JTextField();
        tgasoil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        thoras = new javax.swing.JTextField();
        tincidencias = new javax.swing.JTextField();
        bañadir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bcerrar = new javax.swing.JButton();
        comboV = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 420));
        getContentPane().setLayout(null);

        jLabel1.setText("PARTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(144, 21, 39, 16);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("kilometraje"));

        jLabel2.setText("Iniciales");

        jLabel3.setText("Finales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(tkmfin, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tkmini)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tkmini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tkmfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 180, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos"));

        jLabel4.setText("Gasoil");

        jLabel5.setText("Autopista");

        jLabel6.setText("Dietas");

        jLabel7.setText("Otros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totros, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(tdietas)
                    .addComponent(tgasoil)
                    .addComponent(tautopis))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tgasoil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tautopis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tdietas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 140, 180, 150);

        jLabel8.setText("Horas Trabajadas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 50, 120, 16);
        getContentPane().add(thoras);
        thoras.setBounds(280, 70, 110, 26);
        getContentPane().add(tincidencias);
        tincidencias.setBounds(210, 150, 180, 140);

        bañadir.setText("Añadir Viajes");
        bañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bañadirActionPerformed(evt);
            }
        });
        getContentPane().add(bañadir);
        bañadir.setBounds(27, 320, 140, 29);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 340, 75, 29);

        jLabel9.setText("Indidencias");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 130, 80, 16);

        bcerrar.setText("Cerrar Parte");
        bcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bcerrar);
        bcerrar.setBounds(177, 320, 120, 29);

        comboV.setMaximumRowCount(20);
        getContentPane().add(comboV);
        comboV.setBounds(280, 100, 90, 27);

        jLabel10.setText("Vehiculos");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 100, 60, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fecha=new Date();
       
         if (estadoV.compareToIgnoreCase("cerrado")==0 &&
                 tkmini.getText().isEmpty()==false &&
                 tkmfin.getText().isEmpty()==false &&
                 thoras.getText().isEmpty()==false &&
                 comboV.getItemAt(0).isEmpty()==true) finalizado="t";
                 else 
                 finalizado="f";
      controladora.subirP(fecha,Double.parseDouble(tkmini.getText()),Double.parseDouble(tkmfin.getText()),finalizado,Double.parseDouble(tgasoil.getText()),Double.parseDouble(tautopis.getText()),Double.parseDouble(tdietas.getText()),Double.parseDouble(totros.getText()),tincidencias.getText(),Double.parseDouble(thoras.getText()),comboV.getSelectedItem().toString(),dni_trabaja);
                
        controladora.acabarV();
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bañadirActionPerformed
//aqui que hacer una subida a la base y extraer el idparte
//los campos obligatorios  que no se hayan rellenando se sustituiran por"no rellenado"o 0 que no hayas sido 
        // TODO add your handling code here:
       
        estadoV="abierto";
        
         if (estadoV.compareToIgnoreCase("abierto")==0) finalizado="f";
           fecha=new Date();
        java.sql.Date fechasql = new java.sql.Date(fecha.getTime());
        int idparte;
        
        if(tkmini.getText().isEmpty()==true)tkmini.setText("000000");
           if(tkmfin.getText().isEmpty()==true)tkmfin.setText("000000");
           if(thoras.getText().isEmpty()==true);thoras.setText("000000");
           if(tgasoil.getText().isEmpty()==true)tgasoil.setText("0");
           if (tautopis.getText().isEmpty()==true)tautopis.setText("0");
           if(tdietas.getText().isEmpty()==true)tdietas.setText("0");
           if(totros.getText().isEmpty()==true)totros.setText("0");
           
           if(comboV.getSelectedIndex()==-1) comboV.setSelectedIndex(0);
       
        idparte=controladora.subirP(fecha,Double.parseDouble(tkmini.getText()),Double.parseDouble(tkmfin.getText()),finalizado,Double.parseDouble(tgasoil.getText()),Double.parseDouble(tautopis.getText()),Double.parseDouble(tdietas.getText()),Double.parseDouble(totros.getText()),tincidencias.getText(),Double.parseDouble(thoras.getText()),comboV.getSelectedItem().toString(),dni_trabaja);  
        controladora.abrirViaje(idparte);
    }//GEN-LAST:event_bañadirActionPerformed

    private void bcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcerrarActionPerformed
        // TODO add your handling code here:
        
     
     int idparte;
     fecha=new Date();
       
         if (estadoV.compareToIgnoreCase("cerrado")==0 &&
                 tkmini.getText().isEmpty()==false &&
                 tkmfin.getText().isEmpty()==false &&
                 thoras.getText().isEmpty()==false &&
                 comboV.getItemAt(0).isEmpty()==true) finalizado="t";
                 else 
                 finalizado="f";
         idparte=controladora.subirP(fecha,Double.parseDouble(tkmini.getText()),Double.parseDouble(tkmfin.getText()),finalizado,Double.parseDouble(tgasoil.getText()),Double.parseDouble(tautopis.getText()),Double.parseDouble(tdietas.getText()),Double.parseDouble(totros.getText()),tincidencias.getText(),Double.parseDouble(thoras.getText()),comboV.getSelectedItem().toString(),dni_trabaja);
                
    }//GEN-LAST:event_bcerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelParte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bañadir;
    private javax.swing.JButton bcerrar;
    private javax.swing.JComboBox<String> comboV;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tautopis;
    private javax.swing.JTextField tdietas;
    private javax.swing.JTextField tgasoil;
    private javax.swing.JTextField thoras;
    private javax.swing.JTextField tincidencias;
    private javax.swing.JTextField tkmfin;
    private javax.swing.JTextField tkmini;
    private javax.swing.JTextField totros;
    // End of variables declaration//GEN-END:variables
}
